site_name: Targeting 2019-nCoV Portal
site_author: David Leon (Dawei Leng)
docs_dir: docs

markdown_extensions:
    - pymdownx.arithmatex

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
    - Home: index.md
    - 2019-nCoV Community Effort: drug_candidates.md
    - Coronavirus Disease Biology and Therapeutics: nCov_Targets.md
    #- 2019-nCoV Assay Protocals: assay.md
    #- 2019-nCoV Computational Studies: computational.md
    - Data Download:
      - Coronavirus Data Mining and Analysis: CoV_Experiment_Data.md
      - 2019-nCoV Structure Modeling: nCov_Structures.md
      - 2019-nCoV Research Articles: research_progress.md
    - Community Discussion: contact_us.md
    - Useful Links: useful_links.md
    - History: history.md

theme: readthedocs    
